apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: image-registry
  annotations:
    consoleName: snippet-image-registry
    consoleTitle: Configure Images, Registry, Tags
    consoleDesc: Use this snippet to specify images, registry, or tags
    consoleSnippet: true
spec:
  imageRegistry:
    insecure: true
    registry: registry.example.com:5000
  objects:
    console:
      image: console-image
      imageContext: test
      imageTag: "1.2"
    servers:
      - image: server-image
        imageContext: test
        imageTag: "1.2"
      - image: server-image2
        imageTag: "1.1"
    smartRouter:
      image: router-image
    processMigration:
      image: pim-image
      imageContext: test
      imageTag: "1.0"